name: flutter_jornal_virtual
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter_svg: ^2.0.0
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: IBMSerif
      fonts:
        - asset: assets/fonts/IBMPlexSerif-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSerif-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/IBMPlexSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSerif-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/IBMPlexSerif-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSerif-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/IBMPlexSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSerif-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/IBMPlexSerif-Bold.ttf
          weight: 700